server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name : cau

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    platform: mysql
    url: jdbc:mysql://causecretarydb.cfoadhgjb3mf.ap-northeast-2.rds.amazonaws.com:3306/causecretary
    username: causecretarydb
    password: smilecau1234
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    hikari:
      connectionInitSql: "SET NAMES 'utf8mb4'"
      leak-detection-threshold: 2000



#
#  #data:
#  datasource:
#    maria:
#      jdbc-url: jdbc:mariadb://causecretary.cwtzlobuufiz.us-east-1.rds.amazonaws.com:3306/causecretary?useUnicode=yes&characterEncoding=UTF-8
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: causecretary
#      password: smilecau1234
#      hikari:
#        connectionInitSql: "SET NAMES 'utf8mb4'"

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234


    oauth2:
      client:
        registration:
          facebook:
            client-id: 315293796826930
            client-secret: 487af9479023b8c0e58f913b411327cf
            scope:
              - public_profile
              - email

secret:
  # private-diary-key: ${PRIVATE_DIARY_KEY}
  jwt-secret-key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK