server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name : swith

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/swith_test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ljp153153
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    hikari:
      connectionInitSql: "SET NAMES 'utf8mb4'"
      leak-detection-threshold: 2000



  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database:


  security:
    user:
      name: test
      password: 1234

  oauth2:
    client:
      registration:
        facebook:
          client-id: 315293796826930
          client-secret: 487af9479023b8c0e58f913b411327cf
          scope:
            - public_profile
            - email



secret:
  # private-diary-key: ${PRIVATE_DIARY_KEY}
  jwt-secret-key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK


file:
  path:
